name: Update streak stats
on:
  schedule:
    - cron: "0 3 * * *" # Berjalan otomatis setiap hari pada pukul 03:00 server
  push:
    paths:
      - ".github/workflows/streak-stats.yml" # Berjalan otomatis jika file ini diperbarui
  workflow_dispatch: # Mengizinkan eksekusi manual melalui tab "Actions"
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - name: Generate streak stats
        uses: DenverCoder1/github-readme-streak-stats@main
        with:
          # Penyesuaian tema dan ukuran sesuai preferensi sebelumnya
          options: user=${{ github.repository_owner }}&theme=github-dark&date_format=j%20M%5B%20Y%5D&card_width=461&card_height=160
          path: profile/streak.svg
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Commit streak stats
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add profile/streak.svg
          git commit -m "Update streak stats" || exit 0
          git push